src/Jasekz/Laradrop/Http/routes.php
<?php 
Route::group(['middleware' => config('laradrop.middleware') ? config('laradrop.middleware') : null], function () {
    
    Route::get('laradrop/containers', [
        'as' => 'laradrop.containers',
        'uses' => '\Jasekz\Laradrop\Http\Controllers\LaradropController@getContainers'
    ]);
    
    Route::post('laradrop/move', [
        'as' => 'laradrop.move',
        'uses' => '\Jasekz\Laradrop\Http\Controllers\LaradropController@move'
    ]);
    
    Route::post('laradrop/create', [
        'as' => 'laradrop.create',
        'uses' => '\Jasekz\Laradrop\Http\Controllers\LaradropController@create'
    ]);
    
    Route::resource('laradrop', '\Jasekz\Laradrop\Http\Controllers\LaradropController');
    
});

src/Jasekz/Laradrop/resources/views/fileContainer.blade.php
<div class="laradrop-thumbnail thumbnail laradrop-droppable col-md-2 laradrop-draggable "  file-id="[[id]]">
    <div class=" well" >
        <h4 class="laradrop-filealias" >[[alias]]</h4>
        <p class="text-info">[[type]] / [[updated_at]]</p>
        <p>
            <a href="#" onclick="return false;" class="label label-success laradrop-file-insert" rel="tooltip" title="{{ trans('laradrop::app.select') }}">{{ trans('laradrop::app.select') }}</a>
            <a href="{{ route('laradrop.index') }}" class="label label-danger laradrop-file-delete" rel="tooltip" title="{{ trans('laradrop::app.delete') }}">{{ trans('laradrop::app.delete') }}</a>
            <a href="#" onclick="return false;" class="label label-warning move" rel="tooltip" title="{{ trans('laradrop::app.move') }}">{{ trans('laradrop::app.move') }}</a>
        </p>
        <img src="[[fileSrc]]" alt="[[alias]]" >
    </div>
</div>

src/Jasekz/Laradrop/resources/views/mainContainer.blade.php
<div class="laradrop-container" id="laradrop-container-[[uid]]" >
    
    <button type="button" class="btn btn-default btn-add-folder">{!! trans('laradrop::app.addFolder') !!}</button>
    <button type="button" class="btn btn-default btn-add-files">{!! trans('laradrop::app.uploadFiles') !!}</button>
    <button type="button" class="btn btn-success start" style="display:none;" >{!! trans('laradrop::app.startUpload') !!}</button>
       
    <div class="laradrop-breadcrumbs-container"></div>    
    <hr>
    
    <div class="laradrop-previews" ></div>
    <div class="laradrop-body" ></div>
</div>

src/Jasekz/Laradrop/resources/views/previewContainer.blade.php
<div class="files">
    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" >
        <div class="progress-bar progress-bar-success"  data-dz-uploadprogress></div>
	</div>
	<div id="template" class="file-row">
        <div>
            <p class="name" data-dz-name></p>
            <strong class="error text-danger" data-dz-errormessage></strong>
        </div>
        <div>
            <p class="size" data-dz-size></p>
        </div>
        
            <button data-dz-remove class="btn btn-danger btn-xs cancel">
                Cancel
            </button>
    </div>
</div>